### PR TITLE
Push new pgdl results to SB

### PR DESCRIPTION
**Pull request by hcorson-dosch**
* Update `col_types` for `posthoc_config.csv` being read from `lake-temperature-neural-networks`
* Committed updated sb log files
* Uncommented pgdl target depends in remake.yml - sorry, @lindsayplatt you'll probably just have to recomment these out. I should probably have just left them.

### CODE REVIEW

**Comment by lindsayplatt** [comment]
That's OK! I might not need to comment out to run. We shall see :)

**Review by lindsayplatt — APPROVED** [review]

**Comment by hcorson-dosch** [comment]
New pgdl results look much improved at the surface:
nhdhr_120020945_depth0_finetune_ribbon_1980,1981,1985,1988,1990,1992,1995,2006,2012,2015,2016
nhdhr_91688455_depth0_finetune_ribbon_1985,1995,2000,2005,2015


As well as at mid depths where we previously saw negative predictions:
nhdhr_167256805_depth3_finetune_ribbon_1980,1982,1990,1993,1994
nhdhr_120018088_depth5_finetune_ribbon_1980,1981,1983,1990,1991,1994-2002,2004,2006-2015,2017,2018

The new median rmse (6/15/21) is 1.71 (previously 1.75)

Comparison of new pgdl rmses (6/15/21) to pgdl rmses in February (2/23/21 - after clarity fix)
compare_rmses_20210615

Comparison of new pgdl rmses (6/15/21) to pb0 rmses (04/08/21)
pgdl_pb0_rmses_20210615

I was also curious whether the degree of monotonicity had changed. I plotted temp profiles (raw and sorted) for the same set of sites and dates that I had previously investigated (tried to find the issue where those were called out but I can't). In general, doesn't look like there was any change -- still seeing some funky profiles:

image
image
image
image
image
image
image
image


I also calculated some summary metrics, but currently can't get an allocation on tallgrass so can't open my jupyter notebook where those metrics are, so I'll add those tomorrow....

**Comment by jread-usgs** [comment]
Great figures!

**Comment by hcorson-dosch** [comment]
Ok got those summary statistics -- on average, across 638 lakes, 75% of profiles were sorted. Among profiles that were sorted, on average 64% of depths were affected by the sorting (e.g., had a different temperature before and after sorting).

Some pretty high numbers, and unfortunately I don't have the same summary for the previous results as I forgot to set the old results aside in a subfolder before rebuilding the pgdl targets in this pipeline, but I remember that the numbers for the sites I explored previously were similarly high. So I don't think the new ice flags had any impact on the degree of monotonicity of the pgdl results.

If we do want a direct comparison, I did save the old pgdl results in the `lake-temperature-neural-networks` repo on Tallgrass, so could rebuild these targets with the old results if needed.

**Pull request merged**
