### PR TITLE
Update PGDL results following negative temp fix

### PR DESCRIPTION
**Pull request by lindsayplatt**
The ice flag fix was then used by Hayley to rerun PGDL temperatures and that fixed the negative temperature issue we were seeing. We paused the data review to get this fix up ASAP. 

Also a tiny little update to the README to fix a formatting issue & add a note about including the gdal module when running this repo to avoid this error (I kept copying the module load command from `lake-temperature-out` which does not include gdal and getting this error).

```r
Error: package or namespace load failed for ‘meddle’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/cxfs/projects/usgs/water/iidd/data-sci/lake-temp/mntoha-data-release/Rlib_3_6/sf/libs/sf.so':
 libproj.so.19: cannot open shared object file: No such file or directory
```

### CODE REVIEW

**Review by hcorson-dosch — APPROVED** [review]
Woohoo! Nice work getting all of that build done on Yeti so quickly!

**Comment by lindsayplatt** [comment]
Going through spot-checks of the thermal metrics output to verify the fix before sending back to reviewer. Looking good so far. This change is striking (top plot = old, bottom plot = with new updates). Notice that the scale on the old plot ends at -10 and the new one at -5. 

image

**Comment by lindsayplatt** [comment]
A couple of other changes noticed:

First, ice on is always Nov/Dec and not into Jan/Feb

image

Next, stratification onset is never in January

image

And lastly, that one lake with a crazy high coef_var for the first 30 days after ice off is no longer 900+! It is still much higher than the others but not as hard to believe.

image

**Comment by lindsayplatt** [comment]
One potential weird thing is that the ratio between the mean epilimnion and mean hypolimnion volumes is really high (> 495k) for one lake (`nhdhr_120020945`). Is this worth investigating?

image

**Comment by hcorson-dosch** [comment]
hmmm so the `mean_hyp_vol` for that lake must be really tiny. That seems odd. I can take a look at the temp predictions for that lake

**Comment by hcorson-dosch** [comment]
Ok took a look at the preds for `nhdhr_120020945` - here are the mean PGDL-predicted temperatures for each depth in each month (over the full period):

image

Looks like on average there is pretty weak stratification.

If I try getting the metalimnion depths on those mean temps for the month of July 
``` r
wtr <- pgdl_preds_depth$mean_temp_7
depths <- pgdl_preds_depth$depth
daily_metalimnion = rLakeAnalyzer::meta.depths(wtr, depths)
```

`daily_metalimnion` = `2.77011393348387 · 9`

If I test with predicted temperatures on 7/15/2013, I get a similar result:

`2.95685830945265 · 9`

So it looks like the `meta.depths` call is returning a value for `meta_bottom` that is 9, which I'm guessing is the same as the max_depth of the lake (I don't have the hypso, but the PGDL predictions go to 9m). So effectively, `hyp_vol = calc_volume(meta_bottom, max(hypso$depths), hypso))` is `hyp_vol = calc_volume(~9, 
~9, hypso))`, which would return a near-zero value. That would explain the super huge `mean_epi_hypo_ratio`, right?

**Comment by lindsayplatt** [comment]
@hcorson-dosch oh wow, great find. Yes, that reasoning behind a near-zero `hyp_vol` makes sense and would translate to a really big `mean_epi_hypo_ratio` since we divide by that number.

**Pull request merged**
