### PR TITLE
Final additions for 7_habitat metadata

### PR DESCRIPTION
**Pull request by lindsayplatt**
Changes following our meeting. Two things to note:

1. In order to get the build environment, I navigated to `lake-temperature-out` on Yeti. Running `scmake()` on a target that has already been built started to rebuild it because I made some slight edits when trying to built the 7K lake dataset. These changes should make no difference to the results, so I don't want to actually rebuild. Instead, I found that I could run [`remake::dump_environment()`](https://github.com/richfitz/remake/blob/e29028b548950a3132ea2d045b7f67344ce22a6b/R/api.R#L636-L642) to get all of the packages loaded instead.
2. I cannot build `out_xml/07_habitat.xml` because of the `spatial_metadata` target needing to be built. Therefore, I cannot use the validator you mentioned in order to troubleshoot it.

### CODE REVIEW

**Review by jread-usgs — APPROVED** [review]

**Comment by aappling-usgs** [comment]
> In order to get the build environment, I navigated to lake-temperature-out on Yeti. Running scmake() on a target that has already been built started to rebuild it because I made some slight edits when trying to built the 7K lake dataset. These changes should make no difference to the results, so I don't want to actually rebuild.

A reminder that this is what `sc_bless` exists to support. There are cons to using it, sure, but in the event that (1) you are totally up to speed on what's happening in the repo, and (2) you're quite confident that the changes will have no effect on a set of targets, I would argue that using `sc_bless` may _add_ to the integrity of the repository, because you won't be skirting the pipeline just to get stuff done.

**Comment by aappling-usgs** [comment]
> I cannot build out_xml/07_habitat.xml because of the spatial_metadata target needing to be built. Therefore, I cannot use the validator you mentioned in order to troubleshoot it.

Should we make `spatial_metadata` into a file so that it can be moved to the shared cache? I think we've hit this particular blocker multiple times in data releases.

**Comment by lindsayplatt** [comment]
I always forget about `sc_bless` and just get flustered when things start to rebuild when I don't want them to!

I think making `spatial_metadata` a file that we can put in a shared cache would be great as long as it isn't a huge file.

**Comment by jread-usgs** [comment]
Writing it to a yaml file probably makes the most sense. That way it can get included in `meddle::render` without any other issues. It should be small enough where we could either check it into the repo or include it in a cache.

**Comment by lindsayplatt** [comment]
@jread-usgs if you get me the spatial_metadata as a file, I could work on the next step of generating the habitat XML and using the metadata validator to troubleshoot.

**Comment by jread-usgs** [comment]
will email the file. Turns out it is pretty simple and is 

```yaml
wbbox: -96.8588358
ebbox: -90.036237
nbbox: 49.3749962
sbbox: 43.5115807
feature-ref: Vector
feature-type: G-polygon
feature-count: 881
states:
- state-name: Minnesota
  state-abbr: MN
- state-name: South Dakota
  state-abbr: SD

```

**Comment by lindsayplatt** [comment]
# Build habitat XML

Alright, I have successfully generated the `out_xml/07_habitat.xml` file by editing the `spatial_metadata` target in `1_spatial.yml` to use the file Jordan emailed (see below). I will not be checking this change in as it was just a temporary workaround, but there is an open PR to decide if a file target is more appropriate (see ).

```
# BEFORE
spatial_metadata:
    command: extract_feature(modeled_lakes_sf)

# AFTER
spatial_metadata:
    command: yaml.load_file("mntoha_spatial_metadata.yml")
```

# Validate habitat XML

Then, I ran the xml file through [the validator](https://mrdata.usgs.gov/validation/). I don't know exactly how to interpret, but it does say "No errors", although it also talks about potential issues with the `Bounding_Coordinates` and `Description_of_Geographic_Extent`. I think I can link others directly to the results here: https://mrdata.usgs.gov/validation/phpUxKTdx-summary.html. 

image

I did go through the secondary checklist provided. 

image

1. Not sure what the last two keywords are. They don't match anything in [the thesaurus](https://apps.usgs.gov/thesaurus/thesaurus-full.php?thcode=15) and I don't see them in the repo ymls.

image

2. There is a metadata standard name and version, but I don't know how to tell if they are correct? Also, `Profile_Name` doesn't exist anywhere and I don't know if it should.

image

**Comment by jread-usgs** [comment]
@lindsayplatt sorry for the delay

The Theme 007 and 012 are hard-coded in the xml template [here](https://github.com/USGS-R/meddle/blob/22a6f0c7998b10102a3c4fc8d0b51b6eabc00656/inst/extdata/FGDC_template.mustache#L71)

Alison has brought this up in the past as a question and I am not really sure what do change on this one, other than to acknowledge we probably don't want those hard-coded and I think they are hold overs from earlier releases where we thought those were important themes to include. 

I think at this point we can call this done, but if you'd like a more satisfying answer, I think we need to connect w/ Viv's sciencebase team and get some advice on how to modify the template to deal with some of these complicated fields that we're struggling to figure out.

**Comment by aappling-usgs** [comment]
My recent solution was to use a [custom FGDC template](https://github.com/USGS-R/rahmani_erl_data_release/blob/7be84280d9abd06bcfc633d716b079bac76f5825/in_text/FGDC_template.mustache#L67-L69) where I removed 007 and 012 (but otherwise really just copied and pasted from `meddle`). That change got us comfortably through review and center director/BAO approval.

Also, when Madison made the data release public on January 5, she wrote,

> One thing that we are starting to check for in metadata is the use of USGS Thesaurus for keywords. I noticed that you didn't use the USGS Thesaurus, but two of your keywords match USGS Thesaurus keywords. So, I went ahead and added a new keyword section to your metadata with these two keywords. I hope that is okay. If you can try to add a USGS Thesaurus keywords section to your metadata in the future, that will help users find your data using the [Science Data Catalog](https://data.usgs.gov/datacatalog/).

This was the addition she made:
```
Theme:
  Theme Keyword Thesaurus: USGS Thesaurus
  Theme Keyword: water resources
  Theme Keyword: water temperature
```

**Comment by jread-usgs** [comment]
Nice! Thanks for the insights Alison.

**Comment by lindsayplatt** [comment]
Ah OK, I truly didn't know that `007` and `012` referred to actual theme keywords (I couldn't get James Bond out of my head I guess 😄). To take those out and add in the "USGS Thesaurus", should I hand-edit the XML file? What's the best way to update?

**Comment by jread-usgs** [comment]
Can you make a template edit in `meddle` and do a PR (change version number too plz)

**Comment by lindsayplatt** [comment]
I cannot assign anyone due to repo permissions, but I have an open PR here: https://github.com/USGS-R/meddle/pull/68

**Comment by lindsayplatt** [comment]
Using the updated `meddle` FGDC template, I regenerated the XML for 07_habitat. I re-ran through the validator and still got `no errors`. I also checked that the new USGS Thesaurus keyword were present and that `007` and `012` were no longer listed as keywords. Then, I ran `scmake("log/07_habitat_xml_sb.csv")` to push these changes to SB and log when it was completed. 

You can now find the updated XML on [the 7_habitat SB item](https://www.sciencebase.gov/catalog/item/5e774355e4b01d509270e2a1) or get to it directly [here](https://www.sciencebase.gov/catalog/file/get/5e774355e4b01d509270e2a1?f=__disk__ce%2F3b%2Fc1%2Fce3bc100f0fcc6615c1b26ffff1a32ef1f75a8b4&transform=1&allowOpen=true) (but must be logged in to SB to see for now).

**Comment by lindsayplatt** [comment]
Based on the previous comments that called the rest of this good to go, I am going to go ahead and merge!

**Pull request merged**
