### PR TITLE
remove source_id column from matched pgdl preds

### PR DESCRIPTION
**Pull request by hcorson-dosch**
* remove `source_id` column from `pgdl_matched_to_observations.csv` within `pgdl_matched_to_observations.zip`
* modify `evaluate_preds()` function to account for reduced # of columns in input dataframe
* push updated `pgdl_matched_to_observations.zip` to science base

### CODE REVIEW

**Review by lindsayplatt — COMMENTED** [review]
When you pushed to SB, did the `log/06_evaluationPGDL_sb.csv` target get updated? It should contain the timestamp for your update

**Comment by hcorson-dosch** [comment]
It didn't, and I was wondering why. I had just re-built `out_data/pgdl_evaluation.csv`, but wasn't sure if b/c the content didn't change, scipiper decided not to replace it on SB? This was the output from the command to build `log/06_evaluationPGDL_sb.csv`:

```> scmake('log/06_evaluationPGDL_sb.csv')
Starting build at 2021-03-02 15:33:01
<  MAKE > log/06_evaluationPGDL_sb.csv
[    OK ] sb_id_06_evaluation
[    OK ] export_start
[    OK ] export_stop
[    OK ] pgdl_lake_ids
[    OK ] spatial_groups
[    OK ] pgdl_test_predictions_df
[    OK ] pgdl_test_site_ids
[    OK ] out/pgdl_predictions_test_sorted.ind
[    OK ] modeled_lake_ids
[    OK ] pgdl_lakes_sf
[    OK ] pgdl_centroids_sf
[    OK ] pgdl_site_ids_grouped
[    OK ] out/5_pgdl_test_predictions_zips.yml
[    OK ] tmp/filtered_observations.rds
[    OK ] out_data/temperature_observations.zip
[    OK ] out_data/pgdl_matched_to_observations.zip
[    OK ] out_data/pgdl_evaluation.csv
[ BUILD ] log/06_evaluationPGDL_sb.csv              |  sb_replace_files("log...
Run all tasks and finalizers with:
your_target_name_1:
  command: scmake(I('upload_5e774324e4b01d509270e29f_timestamps'), remake_file='/caldera/projects/usgs/water/iidd/datasci/lake-temp/mntoha-data-release/file_upload_tasks.yml')
### Starting loop attempt 1 of 3 with 1 of 2 tasks remaining:                       
All tasks complete [========================================================] 100%  

### Final check for completeness of all targets
Starting build at 2021-03-02 15:33:10
<  MAKE > file_upload_tasks
[    OK ] sb_5e774324e4b01d509270e29f_pgdl_matched_to_observat...
[    OK ] sb_5e774324e4b01d509270e29f_pgdl_evaluation.csv_file
[ BUILD ] upload_5e774324e4b01d509270e29f_timestamps              |  upload_...
[ ----- ] file_upload_tasks
Finished build at 2021-03-02 15:33:10
Build completed in 0.00 minutes
(   DEL ) upload_5e774324e4b01d509270e29f_timestamps              |  rm("upl...
Finished build at 2021-03-02 15:33:13
Build completed in 0.19 minutes
```

**Comment by hcorson-dosch** [comment]
It did - here are the contents:
	filepath	sb_id	time_uploaded_to_sb
1	out_data/pgdl_matched_to_observations.zip	5e774324e4b01d509270e29f	2021-03-02 21:33 UTC
2	out_data/pgdl_evaluation.csv	5e774324e4b01d509270e29f	2021-02-23 19:54 UTC

**Comment by lindsayplatt** [comment]
Oh, great! So that log/ CSV file should be something that is modified and the changes committed to Git

**Comment by hcorson-dosch** [comment]
oh ok - I'll track it. None of those log files are tracked currently on Tallgrass

**Review by lindsayplatt — APPROVED** [review]

**Pull request merged**
